global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ec2-instance"
    ec2_sd_configs:
      - region: "ap-east-1"
    relabel_configs:
      - source_labels: ["openvpn"]
        regex: node-exporter
        action: keep
    metrics_path: /metrics
    scrape_interval: 15s
  - job_name: "node_exporter"
    static_configs:
      - targets: ["10.10.140.175:9100"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "node_exporter-hkdc01"
    static_configs:
      - targets: ["10.10.0.10:9182"]
    metrics_path: /metrics
    scrape_interval: 15s
  - job_name: "node_exporter-hkdc02"
    static_configs:
      - targets: ["10.10.32.10:9182"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "node_exporter-hkdb01"
    static_configs:
      - targets: ["10.10.0.100:9182"]
    metrics_path: /metrics
    scrape_interval: 15s
  - job_name: "node_exporter-hkdb02"
    static_configs:
      - targets: ["10.10.32.100:9182"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "node_exporter-jpdc01"
    static_configs:
      - targets: ["10.100.0.10:9182"]
    metrics_path: /metrics
    scrape_interval: 15s
  - job_name: "node_exporter-jpdc02"
    static_configs:
      - targets: ["10.100.32.10:9182"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "node_exporter-jpdb01"
    static_configs:
      - targets: ["10.100.0.100:9182"]
    metrics_path: /metrics
    scrape_interval: 15s
  - job_name: "node_exporter-jpdb02"
    static_configs:
      - targets: ["10.100.32.100:9182"]
    metrics_path: /metrics
    scrape_interval: 15s
